name: runjob

on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools
        sudo apt-get install -y xvfb
        pip install -r requirements.txt

    - name: Execute Python script
      env:
          AZURESTORE: ${{ secrets.AZURESTORE }}
      run: |
        xvfb-run --auto-servernum python -u worker.py
