name: runjob

on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: "3.12"
        
    - name: Set up Chrome and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        wget https://chromedriver.storage.googleapis.com/133.0.6943.53/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        chmod +x chromedriver
        sudo mv chromedriver /usr/local/bin/

    - name: Install missing dependencies
      run: |
        sudo apt-get install -y libatk-bridge2.0-0 libatspi2.0-0 libgbm1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools
        sudo apt-get install -y xvfb
        pip install -r requirements.txt

    - name: Execute Python script
      env:
          AZURESTORE: ${{ secrets.AZURESTORE }}
      run: |
        xvfb-run --auto-servernum python -u worker.py
